<?php


namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

/**
 * 用户api基类
 * Class ApiBase
 * @package app\api\controller
 */
class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args){
        throw new HttpResponseException(show(...$args));
    }
}