<?php


namespace app\api\controller;

/**
 * 需已登录用户才能完成的操作基类
 * Class AuthBase
 * @package app\api\controller
 */
class AuthBase extends ApiBase
{
    public $user_id = 0;
    public $username = '';
    public $access_token = '';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->access_token = $this->request->header('access-token');
        if (!$this->access_token || !$this->isLogin()){
            return $this->show(config("status.not_login"),"用户未登录,请先登录");
        }
    }

    /**
     * 判断用户是否已登录
     */
    public function isLogin(){
        $userInfo = cache(config("redis.token").$this->access_token);
        if (!empty($userInfo['user_id']) && !empty($userInfo['username'])){
            $this->user_id = $userInfo['user_id'];
            $this->username = $userInfo['username'];
            return true;
        }else{
            return false;
        }
    }
}